// task1
let element = document.getElementById("elzero");
console.log(element);
 let elementByClass =  document.getElementsByClassName("element")[0];
 console.log(elementByClass);
let elementByTag = document.getElementsByTagName("div")[0];
console.log(elementByTag);
let elementByName = document.getElementsByName("js")[0];
console.log(elementByName);
let eleymentByQuer = document.querySelector("#elzero");
console.log(eleymentByQuer);
let elementByClass1 = document.querySelector(".element");
console.log(elementByClass1);
let elementByTag1 = document.querySelector("div");
console.log(elementByTag1);
let elementByAttribute = document.querySelector('[name="js"]');
console.log(elementByAttribute);
let allById = document.querySelectorAll("#elzero")[0];
console.log(allById);
let allByClass = document.querySelectorAll(".element")[0];
console.log(allByClass);
let allByTag = document.querySelectorAll("div")[0];
console.log(allByTag);
let allByAttribute = document.querySelectorAll('[name="js"]')[0];
console.log(allByAttribute);
let elementByChildren = document.body.children[0];
console.log(elementByChildren);
let firstChild = document.body.firstElementChild;
console.log(firstChild);
let lastChild = document.querySelector("body > div");
console.log(lastChild);
let elementByChildNodes = document.body.childNodes[1];
console.log(elementByChildNodes);